### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by Rookie-zzj** [JiaweiSheng/CasEE#7]
你好！我的环境是torch1.1，transformers4.9.1会出现以下错误，请问这是什么问题啊？
[1] Traceback (most recent call last):
[2]   File "/project/event/CasEE/main.py", line 10, in <module>
[3]     from transformers import *
[4]   File "/usr/local/lib/python3.6/dist-packages/transformers/pipelines/__init__.py", line 30, in <module>
[5]     from .automatic_speech_recognition import AutomaticSpeechRecognitionPipeline
[6]   File "/usr/local/lib/python3.6/dist-packages/transformers/pipelines/automatic_speech_recognition.py", line 20, in <module>
[7]     from .base import Pipeline
[8]   File "/usr/local/lib/python3.6/dist-packages/transformers/pipelines/base.py", line 43, in <module>
[9]     from ..models.auto.modeling_auto import AutoModel
[10]   File "/usr/local/lib/python3.6/dist-packages/transformers/models/auto/modeling_auto.py", line 116, in <module>
[11]     from ..detr.modeling_detr import DetrForObjectDetection, DetrModel
[12]   File "/usr/local/lib/python3.6/dist-packages/transformers/models/detr/modeling_detr.py", line 1315, in <module>
[13]     class DetrForObjectDetection(DetrPreTrainedModel):
[14]   File "/usr/local/lib/python3.6/dist-packages/transformers/models/detr/modeling_detr.py", line 1333, in DetrForObjectDetection
[15]     @torch.jit.unused
[16] AttributeError: module 'torch.jit' has no attribute 'unused'

**Comment by JiaweiSheng** [comment]
Hi. This problem may be caused by the environment version, which I didn't encounter. Please check the pytorch, CUDA and transformers version.

**Comment by 081416252** [comment]
> 你好！我的环境是torch1.1，transformers4.9.1会出现以下错误，请问这是什么问题啊？ [1] Traceback (most recent call last): [2] File "/project/event/CasEE/main.py", line 10, in [3] from transformers import * [4] File "/usr/local/lib/python3.6/dist-packages/transformers/pipelines/**init**.py", line 30, in [5] from .automatic_speech_recognition import AutomaticSpeechRecognitionPipeline [6] File "/usr/local/lib/python3.6/dist-packages/transformers/pipelines/automatic_speech_recognition.py", line 20, in [7] from .base import Pipeline [8] File "/usr/local/lib/python3.6/dist-packages/transformers/pipelines/base.py", line 43, in [9] from ..models.auto.modeling_auto import AutoModel [10] File "/usr/local/lib/python3.6/dist-packages/transformers/models/auto/modeling_auto.py", line 116, in [11] from ..detr.modeling_detr import DetrForObjectDetection, DetrModel [12] File "/usr/local/lib/python3.6/dist-packages/transformers/models/detr/modeling_detr.py", line 1315, in [13] class DetrForObjectDetection(DetrPreTrainedModel): [14] File "/usr/local/lib/python3.6/dist-packages/transformers/models/detr/modeling_detr.py", line 1333, in DetrForObjectDetection [15] @torch.jit.unused [16] AttributeError: module 'torch.jit' has no attribute 'unused'

我也遇到了同样的错误，请问你解决了吗
